/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppReunioesRouteImport } from './routes/_app.reunioes'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppFeedbacksRouteImport } from './routes/_app.feedbacks'
import { Route as AppDesenvolvimentoRouteImport } from './routes/_app.desenvolvimento'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppColaboradoresRouteImport } from './routes/_app.colaboradores'
import { Route as AppAvaliacoesRouteImport } from './routes/_app.avaliacoes'
import { Route as AppAnalisesRouteImport } from './routes/_app.analises'
import { Route as AppAlertasRouteImport } from './routes/_app.alertas'
import { Route as AppColaboradoresIdRouteImport } from './routes/_app.colaboradores.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReunioesRoute = AppReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbacksRoute = AppFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AppRoute,
} as any)
const AppDesenvolvimentoRoute = AppDesenvolvimentoRouteImport.update({
  id: '/desenvolvimento',
  path: '/desenvolvimento',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresRoute = AppColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesRoute = AppAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalisesRoute = AppAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresIdRoute = AppColaboradoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppColaboradoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AppAlertasRoute
  '/analises': typeof AppAnalisesRoute
  '/avaliacoes': typeof AppAvaliacoesRoute
  '/colaboradores': typeof AppColaboradoresRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/feedbacks': typeof AppFeedbacksRoute
  '/insights': typeof AppInsightsRoute
  '/metas': typeof AppMetasRoute
  '/reunioes': typeof AppReunioesRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alertas': typeof AppAlertasRoute
  '/analises': typeof AppAnalisesRoute
  '/avaliacoes': typeof AppAvaliacoesRoute
  '/colaboradores': typeof AppColaboradoresRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/feedbacks': typeof AppFeedbacksRoute
  '/insights': typeof AppInsightsRoute
  '/metas': typeof AppMetasRoute
  '/reunioes': typeof AppReunioesRoute
  '/': typeof AppIndexRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/analises': typeof AppAnalisesRoute
  '/_app/avaliacoes': typeof AppAvaliacoesRoute
  '/_app/colaboradores': typeof AppColaboradoresRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/desenvolvimento': typeof AppDesenvolvimentoRoute
  '/_app/feedbacks': typeof AppFeedbacksRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/reunioes': typeof AppReunioesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/colaboradores/$id': typeof AppColaboradoresIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alertas'
    | '/analises'
    | '/avaliacoes'
    | '/colaboradores'
    | '/configuracoes'
    | '/desenvolvimento'
    | '/feedbacks'
    | '/insights'
    | '/metas'
    | '/reunioes'
    | '/colaboradores/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alertas'
    | '/analises'
    | '/avaliacoes'
    | '/colaboradores'
    | '/configuracoes'
    | '/desenvolvimento'
    | '/feedbacks'
    | '/insights'
    | '/metas'
    | '/reunioes'
    | '/'
    | '/colaboradores/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/alertas'
    | '/_app/analises'
    | '/_app/avaliacoes'
    | '/_app/colaboradores'
    | '/_app/configuracoes'
    | '/_app/desenvolvimento'
    | '/_app/feedbacks'
    | '/_app/insights'
    | '/_app/metas'
    | '/_app/reunioes'
    | '/_app/'
    | '/_app/colaboradores/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reunioes': {
      id: '/_app/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AppReunioesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedbacks': {
      id: '/_app/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AppFeedbacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/desenvolvimento': {
      id: '/_app/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/desenvolvimento'
      preLoaderRoute: typeof AppDesenvolvimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores': {
      id: '/_app/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AppColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliacoes': {
      id: '/_app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AppAvaliacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analises': {
      id: '/_app/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AppAnalisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores/$id': {
      id: '/_app/colaboradores/$id'
      path: '/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AppColaboradoresIdRouteImport
      parentRoute: typeof AppColaboradoresRoute
    }
  }
}

interface AppColaboradoresRouteChildren {
  AppColaboradoresIdRoute: typeof AppColaboradoresIdRoute
}

const AppColaboradoresRouteChildren: AppColaboradoresRouteChildren = {
  AppColaboradoresIdRoute: AppColaboradoresIdRoute,
}

const AppColaboradoresRouteWithChildren =
  AppColaboradoresRoute._addFileChildren(AppColaboradoresRouteChildren)

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppAnalisesRoute: typeof AppAnalisesRoute
  AppAvaliacoesRoute: typeof AppAvaliacoesRoute
  AppColaboradoresRoute: typeof AppColaboradoresRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDesenvolvimentoRoute: typeof AppDesenvolvimentoRoute
  AppFeedbacksRoute: typeof AppFeedbacksRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMetasRoute: typeof AppMetasRoute
  AppReunioesRoute: typeof AppReunioesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppAnalisesRoute: AppAnalisesRoute,
  AppAvaliacoesRoute: AppAvaliacoesRoute,
  AppColaboradoresRoute: AppColaboradoresRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDesenvolvimentoRoute: AppDesenvolvimentoRoute,
  AppFeedbacksRoute: AppFeedbacksRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMetasRoute: AppMetasRoute,
  AppReunioesRoute: AppReunioesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
